### ISSUE TITLE
Rename project from "ili" to "cili"

### ISSUE THREAD

**Issue by goodmami** [globalwordnet/cili#2]
I propose that this repository, the files within, and references in other GWA projects to this one all use the name "cili" instead of "ili" (or "CILI", I have no opinion regarding upper or lower case).

Being not fully familiar with the projects, I was confused why there are some references to "ili" and some to "cili". @fcbond tells me they are the same, and that "cili" is the name of the project within GWA while "ili" is a more historical general term. It would be good then to always call this project CILI and then possibly explain in the documentation how it relates to the term "ILI".

**Comment by jmccrae** [comment]
I don't object, but perhaps we should consult the whole GWA board on this?

**Comment by goodmami** [comment]
Yes, I think you're right.

And even if the proposal is rejected, this issue then becomes public documentation of that decision (and the issue could still be resolved by providing the appropriate documentation of the CILI <> ILI difference in some places).

**Comment by goodmami** [comment]
I've been thinking about this some more in light of recent discussions, and I think it still makes sense for this particular resource to be called CILI. More specifically, the idea that ILI is the general term and CILI is one instance of an ILI. Geonames, for instance, could contribute its own interlingual index separate from CILI.

A questions then come up: how do we determine which ILI is used by a particular synset? For now CILI IDs are prefixed with "i", but I don't know how scalable that is (Geonames with "g", etc.?). This is probably a question for the 'schemas' project, though.

**Comment by jmccrae** [comment]
I also think it is important to consider Wikidata as an interlingual index (they also use a similar ID scheme with 'Q'). The English WordNet project is compiling a linking between WordNet and all the Q links so we could include this in the future.

**Comment by fcbond** [comment]
Done!
